version: "3.8"

services:
  postgres:
    image: postgres:11.8-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: migrations
